"""add signup verification

Revision ID: 97d8ae157c75
Revises: fc38dd5eaab9
Create Date: 2026-08-10 17:47:34.182790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97d8ae157c75'
down_revision: Union[str, Sequence[str], None] = 'fc38dd5eaab9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signup_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signup_verifications_email'), 'signup_verifications', ['email'], unique=False)
    op.create_index(op.f('ix_signup_verifications_id'), 'signup_verifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signup_verifications_id'), table_name='signup_verifications')
    op.drop_index(op.f('ix_signup_verifications_email'), table_name='signup_verifications')
    op.drop_table('signup_verifications')
    # ### end Alembic commands ###
