"""Initial Studio Jesly schema

Revision ID: fc38dd5eaab9
Revises: 
Create Date: 2026-08-05 16:12:33.543104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc38dd5eaab9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('portfolio', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolio', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('activity_logs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
